services:
  postgres:
    image: postgres:15
    container_name: postgres_all_conference_site
    restart: always
    environment:
      POSTGRES_DB: iaounde_conferences
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "54324:5432"
    networks:
      - iaounde_conferences
    volumes:
      # ✅ GARDER le volume persistant (pour la persistence des données)
      - postgres_data:/var/lib/postgresql/data
      # ✅ GARDER le dump (pour l'initialisation quand le volume est vide)
      - ./dump_conference_informatique.sql:/docker-entrypoint-initdb.d/iaounde_conferences.sql

  conference-iaounde:
    image: lontsi/iaounde:latest
    container_name: conference-iaounde
    restart: unless-stopped
    ports:
      - "5003:5000"
    networks:
      - iaounde_conferences
    depends_on:
      - postgres
    stdin_open: true
    tty: true

networks:
  iaounde_conferences:
    driver: bridge

volumes:
  postgres_data:
    driver: local
